FROM debian:10

ENV LANG=en_US.UTF-8

RUN echo 'deb http://deb.debian.org/debian testing main' | tee /etc/apt/sources.list.d/testing.list \
 && apt-get update \
 && apt-get install -y \
    curl \
    dumb-init \
    zsh \
    htop \
    locales \
    man \
    nano \
    git \
    procps \
    openssh-client \
    sudo \
    vim.tiny \
    lsb-release build-essential wget gdb \
    libssl-dev liblapack-dev libblas-dev ninja-build zlib1g-dev \
    libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev libbz2-dev \
    lsb-release libcurl4-openssl-dev \
  && wget https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz \
  && tar xzf Python-3.8.2.tgz && cd Python-3.8.2 \
  && CCSHARED='-fPIC' ./configure --prefix=/usr --exec-prefix=/usr --enable-shared --enable-optimizations \
  && make altinstall && cd ../ && rm -rf Python-3.8.2* \
  && wget -qO- https://aide-qc.github.io/deploy/aide_qc/debian/PUBLIC-KEY.gpg | apt-key add - \
  && wget -qO- "https://aide-qc.github.io/deploy/aide_qc/debian/focal/aide-qc.list" | tee -a /etc/apt/sources.list.d/aide-qc.list \
  && /usr/bin/pip3.8 install ipopo cmake --user \
  && unlink /usr/bin/python3 && ln -s /usr/bin/python3.8 /usr/bin/python3 \
  && sed -i 's/#!\/usr\/bin\/python3/#!\/usr\/bin\/python3.9/' /usr/bin/lsb_release \
  && sed -i "s/# en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen \
  && locale-gen 
